#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# Generation Parameters
# Name: ${name}
# Model ID: ${model_id}
# Fly Name: ${fly_name}
# Weights File: ${weights_file}

app = '${fly_name}'
primary_region = 'cdg'

[deploy]
wait_timeout = "10m"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
